; ==============================================================================
; PlatformIO Project Configuration File
; ==============================================================================

[platformio]
default_envs = gh1 ; Ubah ke gh2 jika ingin default-nya GH 2
build_cache_dir = .pio/cache

; --- KONFIGURASI GH 1 ---
[config_gh1]
gh_id = 1
fw_id = 100
up_id = 1

; --- KONFIGURASI GH 2 ---
[config_gh2]
gh_id = 2
fw_id = 200
up_id = 2

[origin]
atomic_base = https://your-server.example.com/api
ta_base = https://your-ta-server.example.com/api

[proxy]
relay_base = https://your-relay-server.example.com/api

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_custom.csv
lib_deps =
    bblanchon/ArduinoJson@^7.4.2
    adafruit/RTClib@^2.1.4
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    vshymanskyy/TinyGSM@^0.12.0
    arduino-libraries/NTPClient@^3.2.1
    esp32async/ESPAsyncWebServer@^3.8.0
    esp32async/AsyncTCP@^3.4.7

; Flag Dasar (Digunakan oleh semua)
build_flags =
    -D TINY_GSM_MODEM_SIM800
    -Os
    -D DEBUG_LEVEL=3
    -D TH_URL='"${origin.atomic_base}/thd?gh_id="'
    -D ND_URL='"${origin.atomic_base}/average-sensor-data?gh_id="'
    -D DEVICE_STATUS_POST_URL='"${origin.ta_base}/device_status"'
    -D DEVICE_STATUS_GET_URL_BASE='"${origin.atomic_base}/get-device-status?gh_id="'
    -D FW_UPDATE_URL='"${origin.atomic_base}/get-file/"'
    -D ND_URL_BASE='"${origin.atomic_base}/average-sensor-data?gh_id="'
    -D SCHEDULE_URL='"${origin.ta_base}/gateway/schedule"'
    ; URL Kamera didefinisikan di sini, tapi hanya dipakai logic GH2
    -D CAMERA_STATUS_URL_BASE='"${origin.atomic_base}/camera_status?gh_id="'
    -D RELAY_API_ROOT='"${proxy.relay_base}"'

; ==============================================================================
; ENVIRONMENT KHUSUS GH 1
; ==============================================================================
[env:gh1]
extends = common
upload_protocol = esptool 
; Jika OTA, ganti protocol ke espota dan port ke gateway-gh-1.local
build_flags =
    ${common.build_flags}
    -D GH_ID_CONFIG=${config_gh1.gh_id}
    -D FW_VERSION_ID=${config_gh1.fw_id}

; ==============================================================================
; ENVIRONMENT KHUSUS GH 2
; ==============================================================================
[env:gh2]
extends = common
upload_protocol = esptool
; Jika OTA, ganti protocol ke espota dan port ke gateway-gh-2.local
build_flags =
    ${common.build_flags}
    -D GH_ID_CONFIG=${config_gh2.gh_id}
    -D FW_VERSION_ID=${config_gh2.fw_id}
